[project]
name = "controller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cobs>=1.2.2",
    "numpy>=2.2.6",
    "pyserial>=3.5",
    "rerun-sdk>=0.31.1",
]

[[tool.uv.index]]
name = "piwheels"
url = "https://www.piwheels.org/simple"
