M48
; DRILL file {KiCad 9.0.2} date 2025-07-04T23:02:32+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-04T23:02:32+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X150.16Y-61.45
X155.01Y-61.45
T2
X149.86Y-58.42
X155.31Y-58.42
T3
X115.0Y-60.0
X115.0Y-110.0
X190.0Y-60.0
X190.0Y-110.0
M30
